import { FormEvent, useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

type Event = { event_id:string; name:string; description:string; date:string; location:string; capacity:number; available_seats:number; status:string };
type Registration = { registration_id:string; event_id:string; ticket_id:string; status:string; created_at:string };
const api = import.meta.env.VITE_API_BASE_URL?.replace(/\/$/, "") || "http://127.0.0.1:3000";
const displayDate = (date:string) => new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(date));
const status = (event:Event) => event.status !== "OPEN" ? "CLOSED" : event.available_seats === 0 ? "FULL" : event.available_seats <= Math.max(5, event.capacity*.15) ? "LIMITED" : "AVAILABLE";

async function request<T>(path:string, init?:RequestInit):Promise<T> {
  const res = await fetch(`${api}${path}`, {headers:{"Content-Type":"application/json",...(init?.headers||{})},...init});
  const payload = await res.json(); if (!res.ok) throw new Error(payload.error?.message || "Something went wrong."); return payload.data;
}

function App(){
 const [events,setEvents]=useState<Event[]>([]), [selected,setSelected]=useState<Event|null>(null), [query,setQuery]=useState(""), [loading,setLoading]=useState(true), [error,setError]=useState(""), [ticket,setTicket]=useState<{registration:Registration;event:Event;name:string;email:string}|null>(null), [lookup,setLookup]=useState<Registration[]|null>(null), [lookupEmail,setLookupEmail]=useState(""), [toast,setToast]=useState("");
 const load=()=>{setLoading(true);setError("");request<{events:Event[]}>("/events").then(x=>setEvents(x.events)).catch(e=>setError(e.message)).finally(()=>setLoading(false));};
 useEffect(load,[]);
 const filtered=useMemo(()=>events.filter(e=>`${e.name} ${e.location}`.toLowerCase().includes(query.toLowerCase())),[events,query]);
 const show=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),3500)};
 async function find(e:FormEvent){e.preventDefault();try{setLookup(await request<{registrations:Registration[]}>(`/registrations/${encodeURIComponent(lookupEmail)}`).then(x=>x.registrations));}catch(err){show(err instanceof Error?err.message:"Could not find registrations");}}
 async function cancel(id:string){if(!confirm("Cancel this registration? Your seat will be released immediately."))return;try{await request(`/registration/${id}`,{method:"DELETE"});show("Registration cancelled.");setLookup(v=>v?.map(x=>x.registration_id===id?{...x,status:"CANCELLED"}:x)||null);load();}catch(err){show(err instanceof Error?err.message:"Cancellation failed");}}
 return <><header><a className="brand" href="#top">gatherly<span>•</span></a><nav><a href="#events">Discover</a><a href="#find">My registrations</a></nav><button className="outline" onClick={()=>document.getElementById("events")?.scrollIntoView()}>Explore events</button></header>
 <main id="top"><section className="hero"><p className="eyebrow">CURATED EXPERIENCES · ACCRA</p><h1>Meet the people<br/><i>moving things forward.</i></h1><p className="lede">Thoughtful gatherings for curious people. Find your next conversation, workshop, or big idea.</p><a className="primary" href="#events">Find an event <b>→</b></a><div className="hero-meta"><span>01</span><span>ONE PLATFORM, REAL CONNECTION</span></div></section>
 <section id="events" className="discover"><div className="section-head"><div><p className="eyebrow">UPCOMING</p><h2>Find your room.</h2></div><label className="search"><span>⌕</span><input aria-label="Search events" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search events or locations"/></label></div>
 {loading&&<div className="cards skeleton"><div/><div/><div/></div>}{error&&<div className="state"><p>{error}</p><button onClick={load}>Try again</button></div>}
 {!loading&&!error&&<div className="cards">{filtered.map((event,i)=><article className="card" key={event.event_id}><div className={`art art-${i%3}`}><span>{new Date(event.date).toLocaleString(undefined,{month:"short"}).toUpperCase()}<strong>{new Date(event.date).getDate()}</strong></span><em>{status(event)}</em></div><div className="card-copy"><p className="eyebrow">{event.location}</p><h3>{event.name}</h3><p>{displayDate(event.date)}</p><div><span>{event.available_seats} seats left</span><button disabled={status(event)!=="AVAILABLE"&&status(event)!=="LIMITED"} onClick={()=>setSelected(event)}>{status(event)==="FULL"?"Sold out":"View event →"}</button></div></div></article>)}</div>}{!loading&&!error&&!filtered.length&&<div className="state">No events match that search.</div>}</section>
 <section id="find" className="find"><div><p className="eyebrow">ALREADY BOOKED?</p><h2>Your plans, all in one place.</h2><p>Enter the email address you used when registering. We only show minimal ticket details.</p></div><form onSubmit={find}><label>Email address<input required type="email" value={lookupEmail} onChange={e=>setLookupEmail(e.target.value)} placeholder="you@example.com"/></label><button className="primary">Find my registration</button></form>{lookup&&<div className="results">{lookup.length?lookup.map(r=><div key={r.registration_id}><b>{events.find(e=>e.event_id===r.event_id)?.name||r.event_id}</b><span>{r.status} · {r.ticket_id}</span>{r.status==="ACTIVE"&&<button onClick={()=>cancel(r.registration_id)}>Cancel</button>}</div>):<p>No registrations found.</p>}</div>}</section></main>
 {selected&&<RegistrationModal event={selected} close={()=>setSelected(null)} done={(registration,name,email)=>{setTicket({registration,event:selected,name,email});setSelected(null);load();}}/>}{ticket&&<Ticket ticket={ticket} close={()=>setTicket(null)}/>} {toast&&<div role="status" className="toast">{toast}</div>}<footer>© 2026 Gatherly. Built for meaningful attendance.</footer></>;
}
function RegistrationModal({event,close,done}:{event:Event;close:()=>void;done:(r:Registration,n:string,e:string)=>void}){const [name,setName]=useState(""),[email,setEmail]=useState(""),[busy,setBusy]=useState(false),[err,setErr]=useState("");async function submit(e:FormEvent){e.preventDefault();setBusy(true);setErr("");try{const r=await request<Registration>("/register",{method:"POST",body:JSON.stringify({event_id:event.event_id,name,email})});done(r,name,email)}catch(x){setErr(x instanceof Error?x.message:"Please try again.")}finally{setBusy(false)}}return <div className="modal-back" role="presentation"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="register-title"><button className="close" onClick={close} aria-label="Close">×</button><p className="eyebrow">RESERVE YOUR SEAT</p><h2 id="register-title">{event.name}</h2><p>{displayDate(event.date)} · {event.location}</p><form onSubmit={submit}><label>Full name<input autoFocus required minLength={2} maxLength={120} value={name} onChange={e=>setName(e.target.value)} /></label><label>Email address<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} /></label>{err&&<p className="form-error">{err}</p>}<button className="primary" disabled={busy}>{busy?"Saving your seat…":"Confirm registration →"}</button></form></section></div>}
function Ticket({ticket,close}:{ticket:{registration:Registration;event:Event;name:string;email:string};close:()=>void}){return <div className="modal-back"><section className="ticket" role="dialog" aria-modal="true"><button className="close" onClick={close} aria-label="Close">×</button><p className="eyebrow">YOU'RE ON THE LIST</p><h2>Registration successful.</h2><div className="ticket-data"><span>EVENT<b>{ticket.event.name}</b></span><span>WHEN<b>{displayDate(ticket.event.date)}</b></span><span>WHERE<b>{ticket.event.location}</b></span><span>TICKET ID<b>{ticket.registration.ticket_id}</b></span></div><p className="ticket-id">{ticket.name} · {ticket.email}</p><button className="outline" onClick={()=>window.print()}>Print ticket</button></section></div>}
createRoot(document.getElementById("root")!).render(<App/>);
